name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build theme
      run: npm run bundle

    - name: Extract theme locally
      run: |
        # Utiliser Python pour extraire sans vérification de sécurité
        python3 -c "
import zipfile
import os
print('Extracting st-jo.zip...')
with zipfile.ZipFile('st-jo.zip', 'r') as zip_ref:
    zip_ref.extractall('.')
    print(f'Extracted {len(zip_ref.namelist())} files')
"
        ls -la st-jo/

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H -p ${{ secrets.SSH_PORT || 22 }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Install tools
      run: sudo apt-get update && sudo apt-get install -y sshpass rsync

    - name: Create backup on server
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -p ${{ secrets.SSH_PORT || 22 }} \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'ENDSSH'
          # Variables
          THEME_PATH="${{ secrets.THEME_PATH }}"
          BACKUP_DIR="${{ secrets.BACKUP_DIR }}/$(date +%Y%m%d_%H%M%S)"
          
          # Créer une sauvegarde du thème actuel
          if [ -d "$THEME_PATH" ]; then
            mkdir -p "$BACKUP_DIR"
            cp -r "$THEME_PATH" "$BACKUP_DIR/"
          fi
        ENDSSH

    - name: Deploy theme files
      run: |
        # Utiliser rsync pour synchroniser les fichiers extraits
        sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -avz --delete \
          -e "ssh -p ${{ secrets.SSH_PORT || 22 }}" \
          ./st-jo/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.THEME_PATH }}/

    - name: Set permissions
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -p ${{ secrets.SSH_PORT || 22 }} \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'ENDSSH'
          # Ajuster les permissions
          find "${{ secrets.THEME_PATH }}" -type d -exec chmod 755 {} \;
          find "${{ secrets.THEME_PATH }}" -type f -exec chmod 644 {} \;
        ENDSSH